version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - finance-net
    deploy:
      replicas: 1

  user-service:
    build: ./user-service
    networks:
      - finance-net
    deploy:
      replicas: 2

  transaction-service:
    build: ./transaction-service
    networks:
      - finance-net
    deploy:
      replicas: 2

networks:
  finance-net:
    driver: bridge